services:
  db:
    image: postgres:15
    container_name: gg_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gg_net

  backend:
    build: ./backend
    container_name: gg_backend
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env
    networks:
      - gg_net

  # frontend:
  #   build: ./frontend
  #   container_name: gg_frontend
  #   restart: unless-stopped
  #   networks:
  #     - gg_net

  bot:
    build: ./max_bot
    container_name: gg_bot
    restart: unless-stopped
    env_file: .env
    networks:
      - gg_net

  nginx:
    image: nginx:alpine
    container_name: gg_nginx
    restart: unless-stopped
    depends_on:
      - backend
      - bot
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro  # ← статика напрямую
    networks:
      - gg_net

volumes:
  postgres_data:

networks:
  gg_net:
    driver: bridge