services:
  db:
    image: postgres:15
    container_name: growgood_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - growgood_net

  backend:
    build: ./backend
    container_name: growgood_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"    
    networks:
      - growgood_net

  frontend:
    build: ./frontend
    container_name: growgood_frontend
    restart: always
    depends_on:
      - backend
    env_file: .env
    ports:
      - "3000:3000"    
    networks:
      - growgood_net

  bot:
    build: ./max_bot
    container_name: growgood_bot
    env_file: .env
    restart: always
    ports:
      - "8080:8080"  
    networks:
      - growgood_net

volumes:
  postgres_data:

networks:
  growgood_net:
    driver: bridge
