services:
  db:
    image: postgres:15
    container_name: growgood_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - growgood_net

  backend:
    build: ./backend
    container_name: growgood_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    environment:
      - HOST=0.0.0.0
    expose:
      - "8000"    
    networks:
      - growgood_net

  frontend:
    build: ./frontend
    container_name: growgood_frontend
    restart: always
    depends_on:
      - backend
    env_file: .env
    environment:
      - HOST=0.0.0.0
    expose:
      - "3000"    
    networks:
      - growgood_net

  bot:
    build: ./max_bot
    container_name: growgood_bot
    env_file: .env
    restart: always
    environment:
      - HOST=0.0.0.0
    expose:
      - "8080"  
    networks:
      - growgood_net

  nginx:
    image: nginx:latest
    container_name: helper_nginx
    restart: always
    depends_on:
      - frontend
      - backend
      - bot
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - growgood_net

volumes:
  postgres_data:

networks:
  growgood_net:
    driver: bridge
