services:
  db:
    image: postgres:15
    container_name: gg_db
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gg_backend
    restart: unless-stopped
    depends_on:
      - db
    env_file: .env

  # frontend:
  #   build: ./frontend
  #   container_name: gg_frontend
  #   restart: unless-stopped
  #   depends_on:
  #     - backend

  bot:
    build: ./max_bot
    container_name: gg_bot
    restart: unless-stopped
    env_file: .env
    expose:
      - "8080" 

  nginx:
    image: docker.io/library/nginx:latest
    container_name: gg_nginx
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
      - bot
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro 

volumes:
  postgres_data: