services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: helper_frontend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: helper_backend
    restart: unless-stopped
    ports:
      - "8000:8000"

  max_bot:
    build:
      context: ./max_bot
      dockerfile: Dockerfile
    container_name: helper_bot
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: helper_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend