version: "3.9"

services:
  db:
    image: postgres:15
    container_name: growgood_db
    restart: always
    environment:
      POSTGRES_DB: growgood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - growgood_net

  backend:
    build: ./backend
    container_name: growgood_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/growgood
    expose:
      - "8000"
    networks:
      - growgood_net

  frontend:
    build: ./frontend
    container_name: growgood_frontend
    restart: always
    depends_on:
      - backend
    expose:
      - "3000"
    environment:
      - YANDEX_API_KEY=${YANDEX_API_KEY}
    networks:
      - growgood_net

  max_bot:
    build: ./max_bot
    container_name: growgood_bot
    env_file: .env
    restart: always
    expose:
      - "8080"
    networks:
      - growgood_net

  nginx:
    image: nginx:latest
    container_name: growgood_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.config:/etc/nginx/conf.d/default.conf:ro
      - /etc/ssl/sonchasapps.crt:/etc/ssl/sonchasapps.crt:ro
      - /etc/ssl/certificate.key:/etc/ssl/certificate.key:ro
    depends_on:
      - frontend
      - backend
      - max_bot
    networks:
      - growgood_net

volumes:
  postgres_data:

networks:
  growgood_net:
    driver: bridge
