services:
  db:
    image: postgres:15
    container_name: growgood_db
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - growgood_net

  backend:
    build: ./backend
    container_name: growgood_backend
    restart: always
    depends_on:
      - db
    env_file: .env
    expose:
      - "8000"
    networks:
      - growgood_net

  frontend:
    build: ./frontend
    container_name: growgood_frontend
    restart: always
    depends_on:
      - backend
    env_file: .env
    expose:
      - "3000"
    networks:
      - growgood_net

  max_bot:
    build: ./max_bot
    container_name: growgood_bot
    env_file: .env
    restart: always
    expose:
      - "8080"
    networks:
      - growgood_net

  nginx:
  image: nginx:latest
  container_name: growgood_nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  depends_on:
    - frontend
    - backend
    - max_bot

volumes:
  postgres_data:

